{
 "title": "truenas 23",
 "tags": [
  "infrastructure",
  "nas"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {}
   },
   {
    "name": "drive",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(scale.$server.smart_log_smart.disktemp.*.*), 5)"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(scale.$server.smart_log_smart.disktemp.*.*, 4)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale.$server.system.uptime.uptime"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(scale.$server.system.ram.*)"
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(aggregate(scale.$server.cputemp.temperatures.*, 'median'), 3)"
    }
   ]
  },
  {
   "title": "cpu average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(scale.$server.system.cpu.*)"
    }
   ]
  },
  {
   "title": "load average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "target": "aliasByMetric(scale.$server.system.load.*)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "target": "aliasByNode(scale.$server.net.bond*.*, 3, 4)"
    }
   ]
  },
  {
   "title": "Phisical network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "target": "aliasByNode(scale.$server.net.enp*.*, 3, 4)"
    }
   ]
  }
 ]
}