{
 "title": "truenas",
 "tags": [
  "infrastructure",
  "nas"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "drive",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk percent busy",
   "type": "timeseries",
   "description": "How much of the time does the disk have a request active or pending",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(servers.$server.disk.$disk.disk_io_time.io_time,3)"
    },
    {
     "target": "aliasByNode(servers.truenas_local.disk.dm-*.disk_io_time.io_time, 3)"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "timeseries",
   "description": "How many disk requests are there in the queue",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.truenas_local.disk.dm-*.pending_operations, 3)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.disk.$disk.pending_operations,3)"
    }
   ]
  },
  {
   "title": "Disk Operations/s",
   "type": "timeseries",
   "description": "Unsure what this is exactly since there is a RWD metric on the same.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(perSecond(servers.truenas_local.disk.dm-*.disk_ops.*), 3)"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "timeseries",
   "description": "Unsure what BW means here,  potentially bandwidth i.e. number of Bytes/s",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.truenas_local.disk.dm-*.disk_octets.*, 3, 5)"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(servers.truenas_local.df.mnt-pool{0,1}-*.df_complex.used, 3)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.truenas_local.memory.memory.*)"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(servers.truenas_local.disktemp.*.temperature), 3)"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(servers.truenas_local.disktemp.*.temperature, 3)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "servers.truenas_local.uptime.uptime"
    }
   ]
  },
  {
   "title": "free disk space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(servers.truenas_local.df.mnt-pool{0,1}.df_complex.free, 3)"
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expression": "$A/100", "type": "math" }
   ]
  },
  {
   "title": "cpu average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "aliasByMetric(servers.truenas_local.aggregation.cpu-average.cpu.*)"
    }
   ]
  },
  {
   "title": "load average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "target": "aliasByMetric(servers.truenas_local.load.load.*)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasByNode(servers.truenas_local.interface.bond0.if_octets.*, 3, 5)"
    }
   ]
  },
  {
   "title": "Phisical network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasByNode(servers.truenas_local.interface.enp*s0.if_octets.*, 3, 5)"
    }
   ]
  }
 ]
}